### PR TITLE
Only submit XRGB buffers

### PR DESCRIPTION
**Pull request by mstoeckl**
These two commits resolve https://github.com/swaywm/swaybg/issues/26, by _always_ submitting opaque buffers. This is done by painting the buffers submitted with a uniform color, before drawing the image on top. The default color is chosen to match Sway's default background color, so that most people invoking swaybg under Sway with a semi-transparent (or badly sized `fit` or `center` mode image) will see the same result as before.

I've been undecided about this change for a while, since there is an alternative which preserves the current behavior; to detect  when the output image _may_ be semi-transparent, as a function of the scaling mode, the image size, the presence of the `--color` flag, and whether the image has an alpha channel. However, I don't think allowing transparency in edge cases is a good behavior for a wallpaper program to have, and solving #26 while keeping the current behavior makes the buffer creation logic more complicated, making changes like submitting 10-bit buffers -- for which Cairo only supports the opaque [RGB30 format](https://www.cairographics.org/manual/cairo-Image-Surfaces.html#cairo-format-t) -- harder to implement.

### CODE REVIEW

**Review by rpigott — APPROVED** [review]
Seems reasonable to me. I don't see the utility in transparent backgrounds.

**Comment by emersion** [comment]
The idea sounds reasonable, even if I'm a bit sad to loose transparency support. I think there are very unusual use-cases which would benefit from transparency support, e.g. nested compositors.

Also note, Sway's default background color is now black instead of gray.

**Comment by emersion** [comment]
>      I'm not aware of any compositors with a transparent background; also AFAIK most nested compositors are either used for testing, or are rootless. Swaybg already does not support semi-transparent solid_color backgrounds.

gamescope and cage are nested compositors designed to be run in production, FWIW.

**Comment by mstoeckl** [comment]
> gamescope and cage are nested compositors designed to be run in production, FWIW.

Right, forgot about those; but they are single-application and don't need wallpapers.

**Review by emersion — APPROVED** [review]
LGTM, we can always re-introduce alpha support later on if we decide it's worthwhile.

**Pull request merged**
